=== rmantovani68/oms/MariniImpianto/impianto.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.marini.fayat.com/impianto.xsd"
  xmlns="http://www.marini.fayat.com/impianto.xsd" elementFormDefault="qualified">

  <xs:annotation>
    <xs:documentation xml:lang="en">
      plant schema definition
    </xs:documentation>
  </xs:annotation>

  <!-- Impianto -->

  <xs:element name="Impianto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ZonaPredosaggio"    minOccurs="0" maxOccurs="1" type="zona_predosaggio_type"/>
        <xs:element name="ZonaEssiccazione"   minOccurs="0" maxOccurs="1" type="zona_essiccazione_type"/>
        <xs:element name="ZonaDosaggio"       minOccurs="0" maxOccurs="1" type="zona_dosaggio_type"/>
        <xs:element name="ZonaCisterne"       minOccurs="0" maxOccurs="1" type="zona_cisterne_type"/>
        <xs:element name="ZonaStoccaggio"     minOccurs="0" maxOccurs="1" type="zona_stoccaggio_type"/>
        <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
      </xs:sequence>
      <xs:attributeGroup ref="obj_attributes_group"/>
    </xs:complexType>
  </xs:element>

  <!--                      -->
  <!-- Definizione dei tipi -->
  <!--                      -->

  <!-- ZONA PREDOSAGGIO -->
  <xs:complexType name ="zona_predosaggio_type">
    <xs:sequence>
      <xs:element name="Predosatore" minOccurs="0" maxOccurs="unbounded" type="predosatore_type"/>
      <xs:element name="Bilancia"    minOccurs="0" maxOccurs="unbounded" type="bilancia_type"/>
      <xs:element name="Nastro"      minOccurs="0" maxOccurs="unbounded" type="nastro_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- ZONA ESSICCAZIONE -->
  <xs:complexType name ="zona_essiccazione_type">
    <xs:sequence>
      <xs:element name="Tamburo"   minOccurs="0" maxOccurs="unbounded" type="tamburo_type"/>
      <xs:element name="Elevatore" minOccurs="0" maxOccurs="unbounded" type="elevatore_type"/>
      <xs:element name="Filtro"    minOccurs="0" maxOccurs="unbounded" type="filtro_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- ZONA DOSAGGIO -->
  <xs:complexType name ="zona_dosaggio_type">
    <xs:sequence>
      <xs:element name="Vaglio"      minOccurs="0" maxOccurs="unbounded" type="vaglio_type"/>
      <xs:element name="Bilancia"    minOccurs="0" maxOccurs="unbounded" type="bilancia_type"/>
      <xs:element name="Tramoggia"   minOccurs="0" maxOccurs="unbounded" type="tramoggia_type"/>
      <xs:element name="Mescolatore" minOccurs="0" maxOccurs="unbounded" type="mescolatore_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- ZONA STOCCAGGIO -->
  <xs:complexType name ="zona_stoccaggio_type">
    <xs:sequence>
      <xs:element name="Silos"   minOccurs="0" maxOccurs="unbounded" type="silos_type"/>
      <xs:element name="Navetta" minOccurs="0" maxOccurs="unbounded" type="navetta_type"/>
      <xs:element name="Nastro"  minOccurs="0" maxOccurs="unbounded" type="nastro_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- ZONA CISTERNE -->
  <xs:complexType name ="zona_cisterne_type">
    <xs:sequence>
      <xs:element name="Cisterna" minOccurs="0" maxOccurs="unbounded" type="cisterna_type"/>
      <xs:element name="Nastro"   minOccurs="0" maxOccurs="unbounded" type="nastro_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- NASTRO -->
  <xs:complexType name ="nastro_type">
    <xs:sequence>
      <xs:element name="Motore" minOccurs="0" maxOccurs="unbounded" type="motore_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>


  <!-- TAMBURO -->
  <xs:complexType name ="tamburo_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- TRAMOGGIA -->
  <xs:complexType name ="tramoggia_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- SILOS -->
  <xs:complexType name ="silos_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- NAVETTA -->
  <xs:complexType name ="navetta_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>


  <!-- CISTERNA -->
  <xs:complexType name ="cisterna_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- MESCOLATORE -->
  <xs:complexType name ="mescolatore_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- VAGLIO -->
  <xs:complexType name ="vaglio_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- FILTRO -->
  <xs:complexType name ="filtro_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- PREDOSATORE -->
  <xs:complexType name ="predosatore_type">
    <xs:sequence>
      <xs:element name="Grafico" minOccurs="0" maxOccurs="1" type="grafico_predosatore_type"/>
      <xs:element name="SetPredosatore" minOccurs="0" maxOccurs="unbounded" type="set_predosatore_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
    <xs:attribute name="set" type="xs:integer"/>
  </xs:complexType>

  <!-- SET PREDOSATORE TYPE -->
  <xs:complexType name="set_predosatore_type">

    <xs:attribute name="set" type="xs:integer"/>
    <xs:attribute name="setOra" type="xs:long"/>
    <xs:attribute name="tempoStart"  type="xs:long"/>
    <xs:attribute name="tempoStop" type="xs:long"/>
    <xs:attribute name="cambioManuale" type="xs:boolean"/>

  </xs:complexType>

  <!-- grafico predosatore definition -->
  <xs:complexType name ="grafico_predosatore_type">
    <xs:sequence>
      <xs:element name="Curva" minOccurs="0" maxOccurs="unbounded" type="curva_predosatore_type"/>
    </xs:sequence>
    <xs:attribute name="curvaAttiva" type="xs:integer"/>
  </xs:complexType>

  <!-- curva predosatore definition -->
  <xs:complexType name ="curva_predosatore_type">
    <xs:sequence>
      <xs:element name="ValoreCurva" minOccurs="0" maxOccurs="unbounded" type="valore_curva_type"/>
    </xs:sequence>
    <xs:attribute name="IdMaterialeLog" type="xs:long"/>
  </xs:complexType>

  <!-- valori curva predosatore definition -->
  <xs:complexType name ="valore_curva_type">
    <xs:attribute name="valore" type="xs:integer"/>
    <xs:attribute name="percento" type="PercentType"/>
  </xs:complexType>

  >

  <!-- ELEVATORE -->
  <xs:complexType name ="elevatore_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- Bilancia -->
  <xs:complexType name ="bilancia_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- AMPEROMETRO -->
  <xs:complexType name ="amperometro_type">
    <xs:sequence>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- MOTORE -->
  <xs:complexType name="motore_type">
    <xs:sequence>
      <xs:element name="Amperometro" minOccurs="0" maxOccurs="1" type="amperometro_type"/>
      <xs:element name="Property" minOccurs="0" maxOccurs="unbounded" type="property_type"/>
    </xs:sequence>
    <xs:attributeGroup ref="obj_attributes_group"/>
  </xs:complexType>

  <!-- PROPERTY -->
  <xs:complexType name="property_type">
    <xs:attributeGroup ref="prop_attributes_group"/>
  </xs:complexType>

  <!--                         -->
  <!-- simple types definition -->
  <!--                         -->

  <!-- property type definition -->
  <xs:simpleType name="PropertyTypeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Int"/>
      <xs:enumeration value="Dint"/>
      <xs:enumeration value="Bool"/>
      <xs:enumeration value="Long"/>
      <xs:enumeration value="Real"/>
      <xs:enumeration value="Byte"/>
      <xs:enumeration value="Word"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- persistence type definition -->
  <xs:simpleType name="PersistenceType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Auto"/>
      <xs:enumeration value="Manual"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- stato predosatore type definition -->
  <xs:simpleType name="StatoPredosatoreType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Stop"/>
      <xs:enumeration value="Stopping"/>
      <xs:enumeration value="Start"/>
      <xs:enumeration value="Starting"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- percent type definition -->
  <xs:simpleType name="PercentType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- binddirection type definition -->
  <xs:simpleType name="BindDirectionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Default"/>
      <xs:enumeration value="OneTime"/>
      <xs:enumeration value="OneWay"/>
      <xs:enumeration value="OneWayToSource"/>
      <xs:enumeration value="TwoWay"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- bind type definition -->
  <xs:simpleType name="BindType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PLCTag"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- bool type definition -->
  <xs:simpleType name="BoolType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true"/>
      <xs:enumeration value="false"/>
    </xs:restriction>
  </xs:simpleType>

  <!--                                  -->
  <!--   Attributes groups definitions  -->
  <!--                                  -->

  <!-- Object Attributes Group -->
  <xs:attributeGroup name="obj_attributes_group">
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="handler" type="xs:string"/>
  </xs:attributeGroup>

  <!-- Property Attributes Group -->
  <xs:attributeGroup name="prop_attributes_group">
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="bind" type="xs:string"/>
    <xs:attribute name="handler" type="xs:string"/>
    <xs:attribute name="bindtype" type="BindType"/>
    <xs:attribute name="binddirection" type="BindDirectionType"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="persistence" type="PersistenceType"/>
    <xs:attribute name="propertytype" type="PropertyTypeType"/>
  </xs:attributeGroup>
</xs:schema>

=== rmantovani68/oms/datamodel/XMLFiles/impianto-test.xml
<?xml version="1.0" encoding="utf-8"?>
<Impianto
  xmlns="http://www.marini.fayat.com/impianto.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.marini.fayat.com/impianto.xsd file:///C:/Users/uts.MARINI/Documents/projects/new-project/oms/MariniImpianto/impianto.xsd"
  id="Impianto"
  name="Impianto"
  handler="ImpiantoEventHandler">

  <ZonaPredosaggio id="ZonaPredosaggio" name="Zona Predosaggio">
    <Predosatore id="Predosatore1" name="Predosatore 1">
	  <Motore id="Motore3" name="Motore 3" handler="MotoreEventHandler">
        <Property id="Presente"             name="Presente"            propertytype="Bool" bind="PLCTAG_NM_MOTORE1_Presente"            bindtype="PLCTag" binddirection="OneWayToSource" handler="MotorePropertyHandler"/>
        <Property id="Comando"              name="Comando"             propertytype="Bool" bind="PLCTAG_NM_CMD_SemiAuto_3"              bindtype="PLCTag" binddirection="OneWayToSource" handler="MotorePropertyHandler"/>
        <Property id="Set"                  name="Set"                 propertytype="Int"  bind="PLCTAG_AO_SetMotore03"                 bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Ritorno"              name="Ritorno"             propertytype="Bool" bind="PLCTAG_NM_Ritorno_3"                   bindtype="PLCTag" binddirection="OneWay"  handler="MotorePropertyHandler"/>
        <Property id="Allarme"              name="Allarme"       value="false"      propertytype="Bool"  bind="PLCTAG_NM_AllarmeMotore_3"             bindtype="PLCTag" binddirection="OneWay" handler="MotoreAlarmHandler"/>
        <Property id="Blocco"               name="Blocco"              propertytype="Bool" bind="PLCTAG_NM_BloccoMotore_3"              bindtype="PLCTag" binddirection="OneWay" handler="MotorePropertyHandler"/>
        <Property id="AccesoForzato"        name="AccesoForzato"       propertytype="Bool" bind="PLCTAG_NM_AccesoForzatoPLC_3"          bindtype="PLCTag" binddirection="OneWay" handler="MotorePropertyHandler"/>
        <Property id="SpentoForzato"        name="SpentoForzato"       propertytype="Bool" bind="PLCTAG_NM_SpentoForzatoPLC_3"          bindtype="PLCTag" binddirection="OneWay" handler="MotorePropertyHandler"/>
        <Property id="ValoreAmperometro"    name="ValoreAmperometro"   propertytype="Int"  bind="PLCTAG_NM_MOTORE3_Amperometri_ValScal" bindtype="PLCTag" binddirection="OneWay" handler="MotorePropertyHandler"/>
      </Motore>
      <Property id="Comando"        name="Comando"        propertytype="Bool" bind="PLCTAG_DO_Predosatore1"            bindtype="PLCTag" binddirection="OneWayToSource"/>

      <Property id="Ritorno"        name="Ritorno"        propertytype="Bool" bind="PLCTAG_DI_RitPredosatore1"         bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Termica"        name="Termica"        propertytype="Bool" bind="PLCTAG_DI_TermPredosatore1"        bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Allarme"        name="Allarme"        propertytype="Bool" bind="PLCTAG_DI_AllPred1"                bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Palpatore"      name="Palpatore"      propertytype="Bool" bind="PLCTAG_DI_PalpatorePred1"          bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="LivelloMinimo"  name="LivelloMinimo"  propertytype="Bool" bind="PLCTAG_DI_LivMinPred1"             bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Vibratore"      name="Vibratore"      propertytype="Bool" bind="PLCTAG_DI_VibratoreP1"             bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Livello"        name="Livello"        propertytype="Int"  bind="PLCTAG_AI_LivPredosatore1"         bindtype="PLCTag" binddirection="OneWay"/>

      <Property id="Set"            name="Set"            propertytype="Int"  bind="PLCTAG_AO_SetPredosatore1"         bindtype="PLCTag" binddirection="OneWayToSource"/>
      <Property id="SetLampada"     name="SetLampada"     propertytype="Bool" bind="PLCTAG_DO_LampadaP1"               bindtype="PLCTag" binddirection="OneWayToSource"/>
      <Property id="SetVibratore"   name="SetLampada"     propertytype="Bool" bind="PLCTAG_DO_VibratoreP1"             bindtype="PLCTag" binddirection="OneWayToSource"/>
    </Predosatore>

    <Nastro id="Nastro1" name="Nastro 1">
      <Motore id="Motore1" name="Motore 1" handler="MotoreEventHandler">
        <Property id="Presente"             name="Presente"            propertytype="Bool" bind="PLCTAG_NM_MOTORE1_Presente"            bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Comando"              name="Comando"             propertytype="Bool" bind="PLCTAG_NM_CMD_SemiAuto_1"              bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Set"                  name="Set"                 propertytype="Int"  bind="PLCTAG_AO_SetMotore01"                 bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Ritorno"              name="Ritorno"             propertytype="Bool" bind="PLCTAG_NM_Ritorno_1"                   bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"      value="false" />
        <Property id="Allarme"              name="Allarme"             propertytype="Bool" bind="PLCTAG_NM_AllarmeMotore_1"            bindtype="PLCTag" binddirection="OneWay"           handler="Motore1AlarmHandler"        value="false" />
        <Property id="Blocco"               name="Blocco"              propertytype="Bool" bind="PLCTAG_NM_BloccoMotore_1"              bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="AccesoForzato"        name="AccesoForzato"       propertytype="Bool" bind="PLCTAG_NM_AccesoForzatoPLC_1"          bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="SpentoForzato"        name="SpentoForzato"       propertytype="Bool" bind="PLCTAG_NM_SpentoForzatoPLC_1"          bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="ValoreAmperometro"    name="ValoreAmperometro"   propertytype="Int"  bind="PLCTAG_NM_MOTORE1_Amperometri_ValScal" bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"      value="30"    />
      </Motore>
	  <Motore id="Motore2" name="Motore 2" handler="MotoreEventHandler">
        <Property id="Presente"             name="Presente"            propertytype="Bool" bind="PLCTAG_NM_MOTORE1_Presente"            bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Comando"              name="Comando"             propertytype="Bool" bind="PLCTAG_NM_CMD_SemiAuto_2"              bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Set"                  name="Set"                 propertytype="Int"  bind="PLCTAG_AO_SetMotore02"                 bindtype="PLCTag" binddirection="OneWayToSource"  handler="MotorePropertyHandler"/>
        <Property id="Ritorno"              name="Ritorno"             propertytype="Bool" bind="PLCTAG_NM_Ritorno_2"                   bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="Allarme"              name="Allarme"             propertytype="Bool" bind="PLCTAG_NM_AllarmeMotore_2"             bindtype="PLCTag" binddirection="OneWay"          handler="MotoreAlarmHandler"         value="false" />
        <Property id="Blocco"               name="Blocco"              propertytype="Bool" bind="PLCTAG_NM_BloccoMotore_2"              bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="AccesoForzato"        name="AccesoForzato"       propertytype="Bool" bind="PLCTAG_NM_AccesoForzatoPLC_2"          bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="SpentoForzato"        name="SpentoForzato"       propertytype="Bool" bind="PLCTAG_NM_SpentoForzatoPLC_2"          bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
        <Property id="ValoreAmperometro"    name="ValoreAmperometro"   propertytype="Int"  bind="PLCTAG_NM_MOTORE2_Amperometri_ValScal" bindtype="PLCTag" binddirection="OneWay"          handler="MotorePropertyHandler"/>
      </Motore>
    </Nastro>

  </ZonaPredosaggio>

  <Property id="WatchDog" name="WatchDog" propertytype="Bool" bind="PLCTAG_F_WatchdogPC" bindtype="PLCTag" binddirection="TwoWay" handler="WatchDogPropertyHandler"/>

</Impianto>

=== rmantovani68/oms/manager/sample-files/impianto-test.xml
<?xml version="1.0" encoding="utf-8"?>
<Impianto
  xmlns="http://www.marini.fayat.com/impianto.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.marini.fayat.com/impianto.xsd file:///C:/Users/uts.MARINI/Documents/projects/new-project/oms/MariniImpianto/impianto.xsd"
  id="Impianto"
  name="Impianto"
  type="string">

  <ZonaPredosaggio id="ZonaPredosaggio" name="Zona Predosaggio">
    <Predosatore id="Predosatore1" name="Predosatore 1">
      <Property id="Comando"        name="Comando"        propertytype="Bool" bind="PLCTAG_DO_Predosatore1"            bindtype="PLCTag" binddirection="OneWayToSource"/>

      <Property id="Ritorno"        name="Ritorno"        propertytype="Bool" bind="PLCTAG_DI_RitPredosatore1"         bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Termica"        name="Termica"        propertytype="Bool" bind="PLCTAG_DI_TermPredosatore1"        bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Allarme"        name="Allarme"        propertytype="Bool" bind="PLCTAG_DI_AllPred1"                bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Palpatore"      name="Palpatore"      propertytype="Bool" bind="PLCTAG_DI_PalpatorePred1"          bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="LivelloMinimo"  name="LivelloMinimo"  propertytype="Bool" bind="PLCTAG_DI_LivMinPred1"             bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Vibratore"      name="Vibratore"      propertytype="Bool" bind="PLCTAG_DI_VibratoreP1"             bindtype="PLCTag" binddirection="OneWay"/>
      <Property id="Livello"        name="Livello"        propertytype="Int"  bind="PLCTAG_AI_LivPredosatore1"         bindtype="PLCTag" binddirection="OneWay"/>

      <Property id="Set"            name="Set"            propertytype="Int"  bind="PLCTAG_AO_SetPredosatore1"         bindtype="PLCTag" binddirection="OneWayToSource"/>
      <Property id="SetLampada"     name="SetLampada"     propertytype="Bool" bind="PLCTAG_DO_LampadaP1"               bindtype="PLCTag" binddirection="OneWayToSource"/>
      <Property id="SetVibratore"   name="SetLampada"     propertytype="Bool" bind="PLCTAG_DO_VibratoreP1"             bindtype="PLCTag" binddirection="OneWayToSource"/>
    </Predosatore>

    <Nastro id="Nastro1" name="Nastro 1">
      <Motore id="Motore1" name="Motore 1">
        <Property id="Presente"             name="Presente"            propertytype="Bool" bind="PLCTAG_NM_MOTORE1_Presente"            bindtype="PLCTag" binddirection="OneWayToSource"/>
        <Property id="Comando"              name="Comando"             propertytype="Bool" bind="PLCTAG_NM_CMD_SemiAuto_1"              bindtype="PLCTag" binddirection="OneWayToSource"/>
        <Property id="Set"                  name="Set"                 propertytype="Int"  bind="PLCTAG_AO_SetMotore01"                 bindtype="PLCTag" binddirection="OneWayToSource" />
        <Property id="Ritorno"              name="Ritorno"             propertytype="Bool" bind="PLCTAG_NM_Ritorno_1"                   bindtype="PLCTag" binddirection="OneWay" />
        <Property id="Allarme"              name="Allarme"             propertytype="Int"  bind="PLCTAG_NM_AllarmeMotore_1"             bindtype="PLCTag" binddirection="OneWay"/>
        <Property id="Blocco"               name="Blocco"              propertytype="Bool" bind="PLCTAG_NM_BloccoMotore_1"              bindtype="PLCTag" binddirection="OneWay"/>
        <Property id="AccesoForzato"        name="AccesoForzato"       propertytype="Bool" bind="PLCTAG_NM_AccesoForzatoPLC_1"          bindtype="PLCTag" binddirection="OneWay"/>
        <Property id="SpentoForzato"        name="SpentoForzato"       propertytype="Bool" bind="PLCTAG_NM_SpentoForzatoPLC_1"          bindtype="PLCTag" binddirection="OneWay"/>
        <Property id="ValoreAmperometro"    name="ValoreAmperometro"   propertytype="Int"  bind="PLCTAG_NM_MOTORE1_Amperometri_ValScal" bindtype="PLCTag" binddirection="OneWay"/>
      </Motore>
    </Nastro>

  </ZonaPredosaggio>

  <Property id="WatchDog" name="WatchDog" propertytype="Bool" bind="PLCTAG_F_WatchdogPC" bindtype="PLCTag" binddirection="TwoWay" handler="WatchDogPropertyHandler"/>

</Impianto>
